services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB=plant_manager
    ports:
      - "5432:5432"
    volumes:
      - /home/hian/data:/var/lib/postgresql/data
  
  backend:
    build: ./back-end
    container_name: backend
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    expose:
      - "8000"
    volumes:
      - ./back-end:/app
    env_file:
      - ./back-end/.env

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - '3000:3000'
    restart: always
    volumes:
    - ./front-end:/app
    - ./front-end/node_modules:/app/node_modules
    env_file:
    - ./front-end/.env
    environment:
      - NODE_PATH=/app/node_modules

  websockets:
    container_name: websockets
    build: ./back-end
    command: daphne -b 0.0.0.0 -p 8080 plant_manager.asgi:application
    restart: always
    expose:
      - "8080"
    volumes:
      - ./back-end:/app
    env_file:
      - ./back-end/.env

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/static/:/var/www/static/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend
      - websockets
volumes:
  front-end:
  back-end:


