# Generated by Django 5.1.1 on 2024-09-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0003_alter_userdevice_user_id'),
        ('readings', '0002_alter_action_user_id_alter_reading_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
