# Generated by Django 5.1.1 on 2024-09-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('devices', '0006_alter_userdevice_user_id'),
        ('readings', '0004_alter_action_user_id_alter_reading_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
