# Generated by Django 5.1.1 on 2024-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fertilizing_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='reading_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='soil_humidity',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='sunlight_hours',
            field=models.IntegerField(default=4),
        ),
    ]
