# Generated by Django 5.1.1 on 2024-09-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_token'),
        ('devices', '0003_alter_userdevice_user_id'),
    ]

    operations = [
    ]
