# Generated by Django 5.1.1 on 2024-09-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('devices', '0004_merge_20240928_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
