# Generated by Django 5.1.1 on 2024-09-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_userdevice_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='led',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='water_level',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
