# Generated by Django 5.1.1 on 2024-09-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_led_device_water_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='led',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='device',
            name='water_level',
            field=models.BooleanField(default=None),
        ),
    ]
