# Generated by Django 5.1.1 on 2024-09-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_led_alter_device_water_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='led',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='water_level',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
