# Generated by Django 5.1.1 on 2024-09-24 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('actuator', models.CharField(max_length=31)),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('soil_moisture', models.FloatField()),
                ('air_humidity', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('luminosity', models.FloatField()),
                ('water_level', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
