# Generated by Django 5.1.1 on 2024-09-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_alter_action_user_id_alter_reading_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='user_id',
        ),
    ]
