# Generated by Django 5.1.1 on 2024-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_remove_reading_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
